"""Initial migration

Revision ID: 218de0861b33
Revises: 1ff38809131d
Create Date: 2025-04-07 09:07:36.472344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218de0861b33'
down_revision = '1ff38809131d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
