"""empty message

Revision ID: 4ae8c0d24d09
Revises: 218de0861b33
Create Date: 2025-04-19 19:57:49.098078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae8c0d24d09'
down_revision = '218de0861b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('file_path', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('file_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('uploaded_by', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('uploaded_by')
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_path')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
