"""Add cover_url column

Revision ID: b6a0d81e9025
Revises: 4ae8c0d24d09
Create Date: 2025-04-19 21:24:44.104129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a0d81e9025'
down_revision = '4ae8c0d24d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###
